doc: Fix example of paths associated with Slicer_EXTENSION_SOURCE_DIRS
{{ '{' }} is used instead of { to avoid the following exception:

jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'

See https://cookiecutter.readthedocs.io/en/latest/troubleshooting.html?highlight=escape#i-m-having-trouble-generating-jinja-templates-from-jinja-templates
and https://stackoverflow.com/a/32283447/1539918